spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

database:
  initialize: false

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

database:
  initialize: false

---
spring:
  config:
    activate:
      on-profile: vm
    import: configserver:http://141.22.10.81:8888

database:
  initialize: false
---
spring:
  jpa:
    properties:
      hibernate:
        show_sql: false  # Disable console logging, we'll capture it with the logger
logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF  # For binding parameters
